Radial Glia Subpopulation characteristics

```{r}
library(Seurat)
library(tidyverse)
library(ggplot2)
library(lme4)
```

```{r}
obj <- readRDS('~/Desktop/snRNA-seq R Files 122524/RNA Object.rds')
```

```{r}
radial_glia <- subset(obj, harmony.wnn_res0.4_clusters==2)
radial_glia <- FindSubCluster(radial_glia, cluster = 2, subcluster.name = 'sub', graph.name = 'harmony.wsnn')

```

```{r}
DimPlot(radial_glia, reduction = 'harmony_wnn.umap', group.by = 'sub')
```

```{r}
markers <- c('elavl3',
             'gfap',
             's100b',
             'sox2',
             'kcnj10a',
             'LOC111577263',
             'hsd17b3',
             'srd5a1',
             'cckb',
             'cckbra',
             'esr2b',
             'pgr'
             )
Idents(radial_glia)<- 'sub'
radial_glia$sub <- factor(radial_glia$sub, 
                          levels = c('2_0','2_1',
                                     '2_2','2_3',
                                     '2_4','2_5',
                                     '2_6','2_7',
                                     '2_8','2_9'))
DotPlot(radial_glia, features = markers, group.by = 'sub')+
  coord_flip()+
  theme(axis.text.x = element_text(angle =-90))
```

```{r}
rg_degs <- read.csv('DEG Outputs/radial glia subcluster expresssion DEGs 020625.csv')

rg_degs$issignif <- ifelse(rg_degs$f_m_q.value<0.1 | rg_degs$d_m_q.value<0.1| rg_degs$d_f_q.value<1, '*',NA)

degs <-rg_degs$gene[rg_degs$issignif =='*' & !is.na(rg_degs$issignif)]
```

```{r}
library(biomaRt)
ocellaris_mart <- useEnsembl(biomart = 'genes',
                             dataset = 'aocellaris_gene_ensembl')

 
```

```{r}
ocellaris1 <- getBM(mart = ocellaris_mart,
                                attributes = c('entrezgene_accession',
                                               'description'))

degs_2 = as.data.frame(degs)
ocellaris2 <- ocellaris1%>%
  right_join(degs_2, by = join_by('entrezgene_accession'=='degs' ))
 
```

LOC111568796 - rbfox1

```{r}
markers <- c('elavl3',
             'gfap',
             's100b',
             'sox2',
             'kcnj10a',
             'LOC111577263',
             'hsd17b3',
             'srd5a1',
             'cckb',
             'cckbra',
             'esr2b',
             'LOC111568796', #rbfox1
             'LOC111568069', #androgen receptor
             'nkx2.2a', #glial marker
             'nlgn3a', # support role of probably interacting with neurons
             'nlgn1',
             'nrxn1a',
             'draxina', #dorsal inhibitory axon guidance protein
             'grid2', #glu receptor
             'apba2b',
             'npy',
             'chd2', #chromodomain helicase
             'aldh1a2' #glia marker
             )
Idents(radial_glia)<- 'sub'
radial_glia$sub <- factor(radial_glia$sub, 
                          levels = c('2_0','2_1',
                                     '2_2','2_3',
                                     '2_4','2_5',
                                     '2_6','2_7',
                                     '2_8','2_9'))
DotPlot(radial_glia, features = markers, group.by = 'sub')+
  coord_flip()+
  theme(axis.text.x = element_text(angle =-90))
```

rbfox kind of everywhere
